# Generated by Django 3.0.6 on 2020-05-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200530_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='job',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Job'),
        ),
    ]
