# Generated by Django 3.0.6 on 2020-06-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_account_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='passwrod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
