# Generated by Django 3.0.6 on 2020-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200605_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='specializes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
