# Generated by Django 3.0.6 on 2020-05-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
