# Generated by Django 3.0.6 on 2020-06-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200604_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Job'),
        ),
    ]
